
links0 = {u'aggregate_link': u'http://bit.ly/Wozuff',
          u'cities': u'gb',
          u'content': u"Of all the bands named after cute animals, Foals are definitely in the top five. Maybe someone should compile a list so it's official. Anywho, the Oxford quintet have laid down visuals for second single My Number \xa0from their incendiary third album, Holy Fire (out 11 Feb). Taking the basic live performance format and contorting it, pray privy to the ebullience of a slo-mo moshpit, the mundanity of the girls' bathroom\xa0and the surreal sight of a dancing trio of girls outside the venue.\xa0",
          u'domain': u'asos.com',
          u'h2': [u'The new music cocktail',
          u'by Karmel Mandrick, 24 January 2013',
          u'Latest Posts',
          u'Categories',
          u'Follow Us',
          u'We Love',
          u'get in touch',
          u'Questions?',
          u"What's in Store",
          u'Follow ASOS',
          u'More about ASOS',
          u'More ASOS sites'],
          u'h3': [u'Post navigation', u"Visit ASOS's international sites:"],
          u'initial': u'20130124122036',
          u'initial_epoch': u'1359030036000',
          u'lang': u'en',
          u'last_indexed_epoch': u'1359041500586',
          u'lastindexed': u'20130124153140',
          u'lastseen': u'20130124153106',
          u'page': u'http://blogs.asos.com/press-play/post/foals---my-number-(video)',
          u'referrer': [u'asos.to', u't.co', u'direct', u'hootsuite.com'],
          u'score': 728.5404,
          u'site': u'blogs.asos.com',
          u'summaryText': u"Of all the bands named after cute animals, Foals are definitely in the top five. Maybe someone should compile a list so it's official. Anywho, the Oxford quintet have laid down visuals for second single My Number \xa0from their incendiary third album, Holy",
          u'summaryTitle': u'FOALS - MY NUMBER (VIDEO)',
          u'title': u'FOALS - MY NUMBER (VIDEO)',
          u'type': u'search',
          u'url': u'http://blogs.asos.com/press-play/Post/foals---my-number-(video)?WT.mc_id=7797&WT.tsrc=Social%20Campaigns'}

links1 = {u'aggregate_link': u'http://bit.ly/W2Ebye',
 u'cities': u'gb',
 u'content': u'Mozart pleases his public The years 1650 to 1750 were a period of\xa0feverish invention and technical ingenuity in music that reached an apotheosis in Handel\'s sublime oratorios and Bach\'s cantatas and Passions. Bach was probably the cleverest composer who ever lived; the mind-boggling complexity of much of his late\xa0music, in particular, has yet to be matched by any composer. But, as often happens in musical history, the generation after Bach stripped away much of the older composers\' harmonic complexity, writing instead with a dramatically simpler palette of harmonies. The likes of Gluck, Mozart and Haydn created a whole new style based on, essentially, four major chords. Much of their music is based on the tonic, dominant and subdominant \u2013 just like much of rock\'n\'roll. Status Quo and the Ramones, say, have shown that the old formulas are the best. Some of Mozart\'s most memorable tunes in his opera The Magic Flute are based on very simple harmonic blocks of three or four chords. Mozart \u2013 unlike most composers before him \u2013 was able to make a living independent of an institution or a single aristocratic patron, but he lived or died by what the public wanted to hear. If people came to hear one of his operas a second time, he made more money on receipts. He twigged that great tunes were what people were drawn to, and that if he enticed and delighted his audience he was more likely not only to get another commission, but also people were more likely to return to hear his works a second and third time if his tunes were memorable. Mozart was a melodic genius. The perfection of the shape of his tunes is what strikes me, his wonderful sense of the rise and fall of a tune and what makes it catch the ear. Those great melodies embed themselves in our heads. This gift for melodies is very rare. I think Mendelssohn, too, a century later, was a composer who had an incredibly easy natural gift and wrote some very nice tunes. In my lifetime? Carole King has written beautiful songs, but only a handful. Richard Rodgers was someone who couldn\'t not write a decent tune. But if you want the sheer unstoppable flow of\xa0Mozart, or Schubert, then you only have Lennon and McCartney. Schubert invents the three-minute pop song Most pop songs are based on a dozen or so of the most familiar chord sequences that were "discovered" in the late 18th century. In the present age, someone such as Adele is an original singer because of her voice, her attitude and her style. But the chords and sequences she and most pop writers are using have been around for a very long time. Perhaps the originator of the\xa0three-minute pop song was John Dowland, way back in Shakespeare\'s time, but I think the modern pop song was created by Schubert. Schubert was a remarkable talent. Melodies poured out of him. He wrote 600 songs, and, like today\'s songwriters, his intention was to write music that would be instantly enjoyable. There\'s not a moment where he is trying to catch you out or where you have to listen 10 times before you get your head around a song. He wants you to get it first time; there\'s verse-chorus, voice and piano underneath, and he wants you to remember the chorus. Some of these simple rules of\xa0songwriting just continue to\xa0be the simple rules of songwriting, and there\'s nothing much about Adele or Simon &\xa0Garfunkel or Leonard Cohen\'s songs that would have seemed alien to the Viennese composer in terms of the chords, or the shape, the way the verse leads into the chorus, or the piano accompaniment. In fact, the thing that would strike Schubert as most odd about an Adele song is the fact that a\xa0woman wrote it rather than being its\xa0object. Schubert came to many of the same conclusions as modern songwriters \u2013 that writing random song after song is no use, that creating 20 songs and a journey is a much more satisfying form. And so that\'s what he did with his song cycles. They are longer pieces where people go on a journey and each song forms the next bit of the story. The fact is that if you strip that all away and ask what it is he is trying to do, he\'s trying to write songs about love (or, let\'s face it, unrequited love) or trying to get to grips with the mysteries of life \u2013 and do so in a way that is instantly enjoyable. He was a young man (by our standards, very young) so there is some naivety to the songs and there\'s a delicacy which, for some people, doesn\'t fit in with the modern world. But leaving that aside, he is trying to create something that is instantly liked by lots of people and enjoyed by them either in their own homes or in a salon. That is not really very different from what Adele is doing. Her songs are based on a piano format, with verse-chorus, addressing the issue of love and romance and shaping the voice around that; emotions are expressed; the length; the format \u2013 Adele wants her songs to be instantly enjoyed. Beethoven and the cult of the\xa0turbulent genius Beethoven changed the point of what music was. He and his music became indivisible: it was a reflection of his inner turmoil. His work sits at the time of a broader cultural movement where artists and poets were doing the same, but what became a musical commonplace was begun by him. Seventies groups such as Yes and Pink Floyd tried to do the same thing and express big ideas in instrumental sections on concept albums. Generally, Beethoven\'s impact has been felt much more strongly in classical music than in pop, because he wrote about his emotions without words. When, at the end of his life, he writes his desperately bleak and private string quartets, it\'s like having a pscyhoanalytic session with him. But the cult of the isolated, divine or demonic genius \u2013 of which Beethoven was the first outstanding musical example \u2013 was developed to a whole new level by Berlioz. We have this French composer to thank for the image of the deranged, hair-challenged, isolated composer, one that persists to this day. He himself was a borderline psychopath at the forefront of the mid-19th century\'s obsession with doomed love, death and destiny, and wrote music on an epic scale, music that would embrace all of life. He was obsessed with Beethoven \u2013 as we still are today, possibly to too great an extent. We\'ve constructed this great building of Beethoven-the-man on top of his music, but if you strip that away and ask what\'s going on in this music, it\'s not always the same thing. Liszt lets music tell the story Beethoven developed the idea that you can tell a story in music. In his Pastoral Symphony he goes for a walk in the country; he sees peasants merry-making, there\'s a thunderstorm \u2026 but that piece is all about the composer, his feelings and his responses. Liszt, however, created the concept that the music itself could tell the story. He moved away from the idea of music as an abstract entity towards orchestral music as a representation of something extra-musical with his symphonic poems. Tasso, Lamento e Trionfo followed the\xa0path of an actual period in the life\xa0of the 16th-century Italian poet \u2013 even weaving in a traditional gondoliers\' folk song and creating an anguished first section about the mental asylum where Tasso was imprisoned for a while. The form of the piece was, crucially, dictated by the story. The climax of his Hunnenschlacht (The Battle of the Huns), devoted to Kaulbach\'s 1850 painting of Attila the Hun\'s battle against the Christian Roman empire, contains the kind of heavyweight flourish you have heard in the scores of countless Hollywood adventure films. In his tone poems, Liszt provided the template for\xa0generations of film composers. If I\xa0was scoring a battle scene for a film, I\xa0would use many of the techniques that Liszt first employed. His influence is enormous, and he had a huge effect on music in the late 19th and early 20th centuries \u2013 so much so that I find myself wondering why we don\'t love him better today. I think it comes down to the fact that he wasn\'t a natural melodist. But to my mind, Liszt is the giant, the key composer of the 19th century, one who turbo-charged music. Dvor\xe1k\'s sampling sparks a debate Composers have always borrowed elements from each other and from ethnic music. Music doesn\'t observe racial or national boundaries. Can you "own" it? Nowhere were the moral questions surrounding this more sharply highlighted that in the US in the late 19th century, where the Czech composer Dvor\xe1k found himself at the centre of a\xa0highly divisive debate. The source melodies for his New World symphony were borrowed \u2013 whether deliberately or absorbed unconsciously \u2013 from Native American and African American folk songs, which raised the question of whether it is legitimate to plunder the music of another community\'s cultural inheritance and place it in an alien and artificial milieu for a very different audience. Dvor\xe1k had only good intentions \u2013 the ennobling of African American culture \u2013 but it\'s important not to see a piece of music isolated from its times. His symphony was written during a period when everything that belonged to Native Americans and African Americans was deliberately being taken away from them by a white culture \u2013 and a work by a European composer performed in a New York concert hall was at that time a piece of white culture. We may never know who wrote the tunes in Dvor\xe1k\'s symphony \u2013 maybe he wrote every note himself. But the conundrums are there nonetheless because it became so commonplace for white musicians to rip off the music of black people. Three decades later, Gershwin, with his Rhapsody in Blue, found himself at the centre of a related debate when his incorporation of jazz \u2013 perceived as grubby, street music \u2013 outraged middle-class concert-goers. Today, there are people who are antagonistic to popular culture of all kinds, who rant about how there\'s nothing good on TV, that young people\'s tastes, habits and fashions are all repellent to them. But it was ever thus.\xa0For a "serious" composer such as\xa0Gershwin to put jazz into a piece of classical music was deeply threatening and played to a fear that, somehow, it would pollute "serious" music. But you can\'t make styles stay apart. They will come together no matter what. As told to Imogen Tilden. Howard Goodall\'s Story of Music begins on BBC2 at 9:30pm on Saturday 26 January. Radio 3\'s The Story of Music in 50 Pieces with Howard Goodall and Suzy Klein begins on 28 January on Essential Classics and In Tune . Goodall\'s book The Story of Music is published by Chatto & Windus, price \xa318.',
 u'description': u"All styles of music feed into each other. Which is why Adele's songs owe everything to Schubert and sampling wouldn't exist without Dvor\xe1k",
 u'domain': u'guardian.co.uk',
 u'h2': [u'Edition: US',
  u'About us',
  u'Subscribe',
  u'Mozart pleases his public',
  u'Schubert invents the three-minute pop song',
  u'Beethoven and the cult of the\xa0turbulent genius',
  u'Liszt lets music tell the story',
  u"Dvor\xe1k's sampling sparks a debate",
  u'Comments',
  u'On the Guardian today'],
 u'h3': [u'Music',
  u'Culture',
  u'Television & radio',
  u'Tigers play with snowmen at safari park',
  u'PSV Eindhoven miss three chances in a row from two yards',
  u'Hilary Mantel on adapting her novels for the stage',
  u'Elk dodges traffic on Moscow motorway',
  u'BBC Sports Personality of the Year \u2013 in pictures',
  u'Dinner, dusk and dancing Russians: my best winter shot',
  u'Monkey adopts kitten \u2013 in pictures'],
 u'initial': u'20130125083805',
 u'initial_epoch': u'1359103085000',
 u'keywords': u'Classical music,Music,Culture,Music TV,Television,Music radio,Radio,Wolfgang Amadeus Mozart,Franz Schubert,Ludwig van Beethoven,Hector Berlioz,Franz Liszt,Anton\xedn Dvo\u0159\xe1k,Adele,Pop and rock,Music',
 u'lang': u'en',
 u'last_indexed_epoch': u'1359111520647',
 u'lastindexed': u'20130125105840',
 u'lastseen': u'20130125105811',
 u'ogtitle': u'What pop music owes to the classical masters',
 u'page': u'http://www.guardian.co.uk/music/2013/jan/24/what-pop-music-owes-classical-masters',
 u'referrer': [u'twittergadget.com',
  u'j.mp',
  u't.co',
  u'direct',
  u'hootsuite.com'],
 u'score': 561.03986,
 u'site': u'www.guardian.co.uk',
 u'summaryText': u"Mozart pleases his public The years 1650 to 1750 were a period of\xa0feverish invention and technical ingenuity in music that reached an apotheosis in Handel's sublime oratorios and Bach's cantatas and Passions. Bach was probably the cleverest composer who",
 u'summaryTitle': u'What pop music owes to the classical masters',
 u'title': u'What pop music owes to the classical masters | Music | The Guardian',
 u'type': u'search',
 u'url': u'http://www.guardian.co.uk/music/2013/jan/24/what-pop-music-owes-classical-masters'}


clicks0 = [{u'clicks': [{u'clicks': 113, u'day_start': 1359003600},
                        {u'clicks': 0, u'day_start': 1358917200},
                        {u'clicks': 0, u'day_start': 1358830800},
                        {u'clicks': 0, u'day_start': 1358744400},
                        {u'clicks': 0, u'day_start': 1358658000}],
            u'global_hash': u'Wozuff',
            u'hash': u'Wozuff',
            u'user_hash': u'Wozuff'}]

clicks1 = [{u'clicks': [{u'clicks': 115, u'day_start': 1359003600},
                        {u'clicks': 0, u'day_start': 1358917200},
                        {u'clicks': 0, u'day_start': 1358830800},
                        {u'clicks': 0, u'day_start': 1358744400},
                        {u'clicks': 0, u'day_start': 1358658000},
                        {u'clicks': 0, u'day_start': 1358571600},
                        {u'clicks': 0, u'day_start': 1358485200}],
            u'global_hash': u'Wozuff',
            u'hash': u'Wozuff',
            u'user_hash': u'Wozuff'}]


link_clicks0 = [{u'clicks': 1, u'dt': 1362456000},
                {u'clicks': 2, u'dt': 1358395200},
                {u'clicks': 2, u'dt': 1357876800},
                {u'clicks': 2, u'dt': 1355976000},
                {u'clicks': 1, u'dt': 1355630400}]

# same number but shifted by 1 day from link_clicks0
link_clicks1 = [{u'clicks': 2, u'dt': 1358395200},
                {u'clicks': 2, u'dt': 1357876800},
                {u'clicks': 2, u'dt': 1355976000},
                {u'clicks': 1, u'dt': 1355630400},
                {u'clicks': 2, u'dt': 1355457600}]

